<?php

namespace Modules\General\Livewire\Security\Permissions;

use App\Livewire\DynamicTable\Table;
use App\Services\NavigationTreeService;
use App\Support\DynamicTable\Core\Columns\TextColumn;
use App\Support\DynamicTable\Core\Filters\TextFilter;
use App\Support\DynamicTable\Core\Sort;
use App\Support\RecordReference\RecordReferenceAccess;
use Illuminate\Database\Eloquent\Builder;
use Spatie\Permission\Models\Permission;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Read-only catalog for the "gen-sec-per" Application (general.security.permissions):
 * every permission name generated by `permissions:sync`, browsable by the
 * module/sub_module/application code prefix it belongs to. Reference only —
 * permissions are system-generated, never created or edited here. Granting
 * one to a department/job title/job title+grade/employee happens on the
 * grantee's own side (e.g. a Rule's Permissions tab, or the HR grant
 * tables), not from this catalog.
 */
class PermissionsTable extends Table
{
    protected string $tableKey = 'general-security-permissions';

    public function boot(): void
    {
        $this->checkAccess();
    }

    public function hydrate(): void
    {
        $this->checkAccess();
    }

    protected function checkAccess(): void
    {
        $application = app(NavigationTreeService::class)->getApplicationByCode('gen-sec-per');

        if (! app(RecordReferenceAccess::class)->applicationAccessible($application)) {
            throw new NotFoundHttpException;
        }
    }

    protected function query(): Builder
    {
        $application = app(NavigationTreeService::class)->getApplicationByCode('gen-sec-per');

        if (! app(RecordReferenceAccess::class)->applicationAccessible($application)) {
            return Permission::query()->whereRaw('1 = 0');
        }

        return Permission::query();
    }

    protected function columns(): array
    {
        return [
            TextColumn::make('name')->sortable()->searchable()->label('Permission'),
            TextColumn::make('guard_name')->sortable()->label('Guard'),
        ];
    }

    protected function filters(): array
    {
        return [
            TextFilter::make('name'),
        ];
    }

    protected function defaultSort(): array
    {
        return [Sort::make('name')->ascending()];
    }
}
