<?php

namespace Modules\Finance\System\AccountsPayable;

use App\Services\NavigationTreeService;
use App\Support\DynamicRecordView\Core\Content\FieldsContent;
use App\Support\DynamicRecordView\Core\DynamicRecordView;
use App\Support\DynamicRecordView\Core\Fields\DateViewField;
use App\Support\DynamicRecordView\Core\Fields\EnumViewField;
use App\Support\DynamicRecordView\Core\Fields\MoneyViewField;
use App\Support\DynamicRecordView\Core\Fields\RecordReferenceViewField;
use App\Support\DynamicRecordView\Core\Fields\RelationViewField;
use App\Support\DynamicRecordView\Core\Fields\TextViewField;
use App\Support\DynamicRecordView\Core\RecordAction;
use App\Support\DynamicRecordView\Core\RecordTab;
use App\Support\DynamicRecordView\Core\SubApplication;
use App\Support\RecordReference\RecordReferenceAccess;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceDeductionLinesTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceLinesTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceTaxLinesTable;
use Modules\Finance\Models\AccountsPayable\ApInvoice;
use Modules\Finance\Models\AccountsPayable\ApInvoiceStatus;
use Modules\Finance\Models\AccountsPayable\VendorProfile;
use Modules\Finance\Services\AccountsPayable\ApInvoiceApprover;

/**
 * The authorized record show page for a single ApInvoice (fin-ap-inv).
 * Mirrors JournalRecordView's shape: header fields, an embedded lines table,
 * and a set of status-gated actions that hand off to the one service
 * (ApInvoiceApprover) that owns every approval rule.
 */
class ApInvoiceRecordView extends DynamicRecordView
{
    protected string $viewKey = 'finance.accounts-payable.invoice';

    public function model(): string
    {
        return ApInvoice::class;
    }

    public function query(): Builder
    {
        $application = app(NavigationTreeService::class)->getApplicationByCode(ApInvoice::APPLICATION_CODE);

        if (! app(RecordReferenceAccess::class)->applicationAccessible($application)) {
            return ApInvoice::query()->whereRaw('1 = 0');
        }

        return ApInvoice::query()->with(['vendorProfile.vendor.company', 'currency']);
    }

    public function title(mixed $record): string
    {
        return $record->invoice_number;
    }

    public function subtitle(mixed $record): ?string
    {
        return $record->status->label().' · '.$record->issue_date->toDateString();
    }

    /**
     * Every button is gated by one fin-ap-inv permission each (update /
     * delete / submit / approve / reject / activate — the last four are the
     * Application's custom_actions, generated by permissions:sync same as
     * Journal's post/reverse/approve).
     */
    public function actions(): array
    {
        return [
            RecordAction::make('edit')
                ->label('Edit')
                ->icon('pencil-square')
                ->permission('update')
                ->variant('primary')
                ->form('finance.accounts-payable.invoice.create')
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),

            RecordAction::make('edit-lines')
                ->label('Edit lines')
                ->icon('table-cells')
                ->permission('update')
                ->variant('filled')
                ->url(fn (mixed $record): string => route('finance.accounts-payable.invoices.lines.edit', ['recordId' => $record->getKey()]))
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),

            RecordAction::make('edit-tax-lines')
                ->label('Edit tax lines')
                ->icon('receipt-percent')
                ->permission('update')
                ->variant('filled')
                ->url(fn (mixed $record): string => route('finance.accounts-payable.invoices.tax-lines.edit', ['recordId' => $record->getKey()]))
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),

            RecordAction::make('edit-deduction-lines')
                ->label('Edit deductions')
                ->icon('minus-circle')
                ->permission('update')
                ->variant('filled')
                ->url(fn (mixed $record): string => route('finance.accounts-payable.invoices.deduction-lines.edit', ['recordId' => $record->getKey()]))
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),

            RecordAction::make('submit')
                ->label('Submit for Approval')
                ->icon('paper-airplane')
                ->variant('filled')
                ->confirm(__('Submit this invoice for approval? It can no longer be edited once submitted.'))
                ->successMessage(__('Invoice submitted for approval.'))
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),

            RecordAction::make('approve')
                ->label('Approve')
                ->icon('check-circle')
                ->variant('filled')
                ->confirm(__('Approve this invoice?'))
                ->successMessage(__('Invoice approved.'))
                ->visible(fn (mixed $record): bool => $record->status === ApInvoiceStatus::PendingApproval),

            RecordAction::make('reject')
                ->label('Reject')
                ->icon('heroicon-o-x-circle')
                ->color('danger')
                ->variant('danger')
                ->confirm(__('Reject this invoice and send it back for correction?'))
                ->successMessage(__('Invoice rejected.'))
                ->visible(fn (mixed $record): bool => $record->status === ApInvoiceStatus::PendingApproval),

            // The terminal human step: turns an approved invoice into one
            // TagERP will actually pay. Kept separate from Approve so the
            // audit trail always shows who approved versus who activated.
            RecordAction::make('activate')
                ->label('Activate')
                ->icon('bolt')
                ->variant('primary')
                ->confirm(__('Activate this invoice? This is the final step before it is payable.'))
                ->successMessage(__('Invoice activated.'))
                ->visible(fn (mixed $record): bool => $record->status === ApInvoiceStatus::Approved),

            RecordAction::make('delete')
                ->label('Delete')
                ->icon('trash')
                ->variant('danger')
                ->confirm(__('Delete this invoice? This cannot be undone.'))
                ->visible(fn (mixed $record): bool => $this->isDraft($record)),
        ];
    }

    public function submit(ApInvoice $record): void
    {
        app(ApInvoiceApprover::class)->submit($this->writable($record), auth()->id());
    }

    public function approve(ApInvoice $record): void
    {
        app(ApInvoiceApprover::class)->approve($this->writable($record), auth()->id());
    }

    public function reject(ApInvoice $record): void
    {
        app(ApInvoiceApprover::class)->reject($this->writable($record), auth()->id());
    }

    public function activate(ApInvoice $record): void
    {
        app(ApInvoiceApprover::class)->activate($this->writable($record), auth()->id());
    }

    public function delete(Model $record): mixed
    {
        $record->delete();

        return route('finance.accounts-payable.invoices');
    }

    /**
     * The instance a record view hands a handler is a display projection
     * with column-narrowed relations; the approver needs the full model,
     * same reasoning as JournalRecordView::writable().
     */
    protected function writable(ApInvoice $record): ApInvoice
    {
        return ApInvoice::findOrFail($record->getKey());
    }

    protected function isDraft(mixed $record): bool
    {
        return $record instanceof ApInvoice && $record->status->isEditable();
    }

    public function tabs(): array
    {
        return [
            RecordTab::make('overview')
                ->label('Overview')
                ->default()
                ->contents([
                    FieldsContent::make('document')
                        ->heading('Document')
                        ->fields([
                            TextViewField::make('invoice_number')->label('Invoice Number'),
                            RecordReferenceViewField::make('vendorProfile')
                                ->applicationCode(VendorProfile::APPLICATION_CODE)
                                ->relation('vendorProfile')
                                ->label('Vendor Profile'),
                            DateViewField::make('issue_date')->label('Issue Date'),
                            DateViewField::make('due_date')->label('Due Date'),
                            RelationViewField::make('currency.name')->label('Currency'),
                            TextViewField::make('po_reference')->label('PO Reference'),
                            EnumViewField::make('status')
                                ->label('Status')
                                ->labels(ApInvoiceStatus::options()),
                        ]),
                    FieldsContent::make('totals')
                        ->heading('Totals')
                        ->fields([
                            MoneyViewField::make('subtotal')->label('Subtotal'),
                            MoneyViewField::make('tax_amount')->label('Tax Amount'),
                            MoneyViewField::make('total_amount')->label('Total Amount'),
                        ]),
                ]),
        ];
    }

    public function subApplications(): array
    {
        return [
            SubApplication::make('lines')
                ->applicationKey('finance.accounts-payable.invoice.lines')
                ->label('Lines')
                ->table(ApInvoiceLinesTable::class)
                ->relation('lines'),

            SubApplication::make('tax-lines')
                ->applicationKey('finance.accounts-payable.invoice.tax-lines')
                ->label('Tax Lines')
                ->table(ApInvoiceTaxLinesTable::class)
                ->relation('taxLines'),

            SubApplication::make('deduction-lines')
                ->applicationKey('finance.accounts-payable.invoice.deduction-lines')
                ->label('Deduction Lines')
                ->table(ApInvoiceDeductionLinesTable::class)
                ->relation('deductionLines'),
        ];
    }
}
