<?php

namespace Modules\Finance\System\GeneralLedger;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\SelectField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\Finance\Models\GeneralLedger\AccountCategory;
use Modules\Finance\Models\GeneralLedger\AccountNature;

/**
 * Create-form definition for the "fin-gl-cat" Application. Code and slug are
 * generated by the model's creating() hook.
 *
 * Normal balance and statement are deliberately absent: both are derived from
 * the nature, so offering them here would only create a way to contradict it.
 */
class AccountCategoryForm extends DynamicForm
{
    public function model(): string
    {
        return AccountCategory::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            SelectField::make('nature')
                ->label('Nature')
                ->options(AccountNature::options())
                ->required()
                ->rules(['in:'.implode(',', array_column(AccountNature::cases(), 'value'))]),
            TextField::make('sort_order')->type('number')->label('Sort Order')->rules(['integer', 'min:0']),
        ];
    }
}
