<?php

namespace Modules\Finance\System\GeneralLedger;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\Finance\Models\GeneralLedger\Account;
use Modules\Finance\Models\GeneralLedger\AccountCategory;

/**
 * Create-form definition for the "fin-gl-acc" Application. Code and slug are
 * generated by the model's creating() hook.
 *
 * Which charts include this account is attached from the chart's own record
 * view, not here — the chart owns its selection.
 */
class AccountForm extends DynamicForm
{
    public function model(): string
    {
        return Account::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('number')->label('Account Number')->required()->rules(['max:50']),
            TextField::make('name')->label('Name')->required(),
            RelationListField::make('parent')
                ->model(Account::class)
                ->field('name')
                ->column('parent_id')
                ->label('Parent Account')
                ->createForm('finance.general-ledger.account.create'),
            RelationListField::make('category')
                ->model(AccountCategory::class)
                ->field('name')
                ->column('category_id')
                ->label('Category')
                ->createForm('finance.general-ledger.account-category.create')
                ->required(),
        ];
    }
}
