<?php

namespace Modules\Finance\System\GeneralLedger;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\TextareaField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\Finance\Models\GeneralLedger\Chart;

/**
 * Create-form definition for the "fin-gl-coa" Application. Code and slug are
 * generated by the model's creating() hook; the accounts a chart includes are
 * attached afterward from its record view.
 */
class ChartForm extends DynamicForm
{
    public function model(): string
    {
        return Chart::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            TextareaField::make('description')->label('Description'),
            TextField::make('levels_count')
                ->type('number')
                ->label('Levels')
                ->required()
                ->rules(['integer', 'min:1', 'max:10']),
        ];
    }
}
