<?php

use App\Models\Permission;
use App\Models\Role;
use Modules\General\Database\Seeders\System\ModulesSeeder;
use Modules\General\Database\Seeders\System\SubModulesSeeder;
use Modules\General\Database\Seeders\World\WorldApplicationsSeeder;
use Modules\General\System\Application;
use Modules\General\System\Module;
use Modules\General\System\SubModule;

/**
 * The entire permission surface of the app is generated by this command, so
 * a typo in one seeder's custom_actions is otherwise silent until someone
 * notices a button nobody can click.
 */
beforeEach(function (): void {
    $this->subModule = SubModule::factory()->create(['code' => 'tst-sub']);
    $this->application = Application::factory()->create([
        'code' => 'tst-sub-app',
        'submodule_id' => $this->subModule->id,
        'custom_actions' => ['post'],
    ]);
});

it('generates the standard actions plus declared custom ones', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    $names = Permission::where('name', 'like', 'tst-sub-app.%')->pluck('name')->all();

    expect($names)->toEqualCanonicalizing([
        'tst-sub-app.view',
        'tst-sub-app.create',
        'tst-sub-app.update',
        'tst-sub-app.delete',
        'tst-sub-app.export',
        'tst-sub-app.print',
        'tst-sub-app.post',
    ]);
});

it('gives navigation nodes only view and update', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    expect(Permission::where('name', 'like', 'tst-sub.%')->pluck('name')->all())
        ->toEqualCanonicalizing(['tst-sub.view', 'tst-sub.update']);
});

it('stamps the view permission onto every node', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    expect($this->application->fresh()->permission_name)->toBe('tst-sub-app.view')
        ->and($this->subModule->fresh()->permission_name)->toBe('tst-sub.view');
});

it('describes each permission in both locales', function (): void {
    $this->application->setTranslations('name', ['en' => 'Journals', 'ar' => 'القيود'])->save();

    $this->artisan('permissions:sync')->assertSuccessful();

    $post = Permission::where('name', 'tst-sub-app.post')->sole();

    expect($post->getTranslation('description', 'en'))->toBe('Post Journals')
        ->and($post->getTranslation('description', 'ar'))->toBe('ترحيل القيود');
});

it('falls back to the raw action for an unmapped custom action', function (): void {
    $this->application->setTranslations('name', ['en' => 'Journals', 'ar' => 'القيود'])->save();
    $this->application->forceFill(['custom_actions' => ['teleport']])->save();

    $this->artisan('permissions:sync')->assertSuccessful();

    expect(Permission::where('name', 'tst-sub-app.teleport')->sole()->getTranslation('description', 'en'))
        ->toBe('teleport Journals');
});

it('is idempotent — a second run creates and updates nothing', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();
    $before = Permission::count();

    $this->artisan('permissions:sync')
        ->expectsOutputToContain('0 created, 0 updated')
        ->assertSuccessful();

    expect(Permission::count())->toBe($before);
});

it('prunes a permission whose custom action was dropped', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();
    expect(Permission::where('name', 'tst-sub-app.post')->exists())->toBeTrue();

    $this->application->forceFill(['custom_actions' => []])->save();
    $this->artisan('permissions:sync')->assertSuccessful();

    expect(Permission::where('name', 'tst-sub-app.post')->exists())->toBeFalse()
        ->and(Permission::where('name', 'tst-sub-app.view')->exists())->toBeTrue();
});

it('prunes every permission of a deleted application', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    $this->application->delete();
    $this->artisan('permissions:sync')->assertSuccessful();

    expect(Permission::where('name', 'like', 'tst-sub-app.%')->count())->toBe(0);
});

it('keeps orphans when pruning is turned off', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    $this->application->delete();
    $this->artisan('permissions:sync', ['--prune' => 0])->assertSuccessful();

    expect(Permission::where('name', 'like', 'tst-sub-app.%')->count())->toBeGreaterThan(0);
});

/**
 * Pruning removes rows other tables point at, so this asserts the grant goes
 * with it rather than leaving a dangling pivot row.
 */
it('takes granted role assignments down with a pruned permission', function (): void {
    $this->artisan('permissions:sync')->assertSuccessful();

    $role = Role::create(['name' => 'Accountant', 'guard_name' => 'web']);
    $role->givePermissionTo('tst-sub-app.post');

    expect($role->fresh()->hasPermissionTo('tst-sub-app.post'))->toBeTrue();

    $this->application->forceFill(['custom_actions' => []])->save();
    $this->artisan('permissions:sync')->assertSuccessful();

    expect(DB::table('role_has_permissions')->where('role_id', $role->id)->count())->toBe(0);
});

it('generates a permission for every seeded application', function (): void {
    $this->seed(ModulesSeeder::class);
    $this->seed(SubModulesSeeder::class);
    $this->seed(WorldApplicationsSeeder::class);

    $this->artisan('permissions:sync')->assertSuccessful();

    foreach (Application::all() as $application) {
        expect(Permission::where('name', "{$application->code}.view")->exists())
            ->toBeTrue("Missing view permission for [{$application->code}]");
    }

    expect(Module::count())->toBeGreaterThan(0);
});
