<?php

namespace Modules\General\System\World;

use App\Support\DynamicForm\Core\CascadingLevel;
use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\CascadingRelationField;
use App\Support\DynamicForm\Core\Fields\TextareaField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\General\Models\World\City;
use Modules\General\Models\World\Companies\Company;
use Modules\General\Models\World\Country;
use Modules\General\Models\World\State;

/**
 * Create-form definition for the "gen-wld-com" Application. Company::code
 * and Company::slug are generated by the model's own creating() hook (see
 * Company::booted()) from name + tax_id — this form only ever supplies the
 * raw business fields.
 */
class CompanyForm extends DynamicForm
{
    public function model(): string
    {
        return Company::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            TextField::make('tax_id')->label('Tax ID'),
            TextField::make('commercial_registration')->label('Commercial Registration'),
            CascadingRelationField::make('city')
                ->level(CascadingLevel::make('country', Country::class)->field('name'))
                ->level(CascadingLevel::make('state', State::class)->field('name')->dependsOn('country'))
                ->level(CascadingLevel::make('city', City::class)->field('name')->dependsOn('state')),
            TextareaField::make('address')->label('Address'),
            TextField::make('phone')->type('tel')->label('Phone'),
            TextField::make('email')->type('email')->label('Email')->rules(['email']),
            TextField::make('website')->type('url')->label('Website'),
        ];
    }
}
