<?php

namespace Modules\General\System\World;

use App\Support\DynamicForm\Core\CascadingLevel;
use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\CascadingRelationField;
use App\Support\DynamicForm\Core\Fields\DateField;
use App\Support\DynamicForm\Core\Fields\SelectField;
use App\Support\DynamicForm\Core\Fields\TextareaField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\General\Models\World\People\Gender;
use Modules\General\Models\World\People\Person;
use Nnjeim\World\Models\City;
use Nnjeim\World\Models\Country;
use Nnjeim\World\Models\State;

/**
 * Create-form definition for the "gen-wld-per" Application. Person::code
 * and Person::slug are generated by the model's own creating() hook (see
 * Person::booted()) from full_name + national_id/passport_number — this
 * form only ever supplies the raw business fields.
 *
 * Job/role history lives in the Positions SubApplication (see
 * PersonRecordView), not here: a Person is created first, then positions
 * are added against the saved record.
 */
class PersonForm extends DynamicForm
{
    public function model(): string
    {
        return Person::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('full_name')->label('Full Name')->required(),
            TextField::make('nickname')->label('Nickname'),
            TextField::make('national_id')->label('National ID'),
            TextField::make('passport_number')->label('Passport Number'),
            SelectField::make('gender')
                ->label('Gender')
                ->options(collect(Gender::cases())
                    ->mapWithKeys(fn (Gender $gender): array => [
                        $gender->value => str($gender->value)->headline()->toString(),
                    ])
                    ->all()),
            DateField::make('date_of_birth')->label('Date of Birth'),
            CascadingRelationField::make('city')
                ->level(CascadingLevel::make('country', Country::class)->field('name'))
                ->level(CascadingLevel::make('state', State::class)->field('name')->dependsOn('country'))
                ->level(CascadingLevel::make('city', City::class)->field('name')->dependsOn('state')),
            TextareaField::make('address')->label('Address'),
            TextField::make('phone')->type('tel')->label('Phone'),
            TextField::make('email')->type('email')->label('Email')->rules(['email']),
        ];
    }
}
