<?php

namespace Modules\Finance\Providers;

use App\Support\DynamicForm\Core\FormDefinitionRegistry;
use App\Support\DynamicRecordView\Core\RecordViewRegistry;
use App\Support\RecordReference\RecordReferenceRegistry;
use Livewire\Livewire;
use Modules\Finance\Livewire\AccountsPayable\DeductionCategories\DeductionCategoriesIndex;
use Modules\Finance\Livewire\AccountsPayable\DeductionCategories\DeductionCategoriesTable;
use Modules\Finance\Livewire\AccountsPayable\DeductionGlLinks\DeductionGlLinksIndex;
use Modules\Finance\Livewire\AccountsPayable\DeductionGlLinks\DeductionGlLinksTable;
use Modules\Finance\Livewire\AccountsPayable\Deductions\DeductionsIndex;
use Modules\Finance\Livewire\AccountsPayable\Deductions\DeductionsTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceDeductionLineEditor;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceDeductionLinesTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceLineEditor;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceLinesTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoicesIndex;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoicesTable;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceTaxLineEditor;
use Modules\Finance\Livewire\AccountsPayable\Invoices\ApInvoiceTaxLinesTable;
use Modules\Finance\Livewire\AccountsPayable\VendorProfiles\VendorProfilesIndex;
use Modules\Finance\Livewire\AccountsPayable\VendorProfiles\VendorProfilesTable;
use Modules\Finance\Livewire\CashAndBanks\BankAccountsTable;
use Modules\Finance\Livewire\CashAndBanks\BankCategoriesTable;
use Modules\Finance\Livewire\CashAndBanks\BankExpenses\BankExpensesIndex;
use Modules\Finance\Livewire\CashAndBanks\BankExpensesTable;
use Modules\Finance\Livewire\CashAndBanks\Banks\Accounts\BankAccountsIndex;
use Modules\Finance\Livewire\CashAndBanks\Banks\BanksIndex;
use Modules\Finance\Livewire\CashAndBanks\Banks\Checks\ChecksIndex;
use Modules\Finance\Livewire\CashAndBanks\Banks\ChecksBooks\ChecksBooksIndex;
use Modules\Finance\Livewire\CashAndBanks\BanksTable;
use Modules\Finance\Livewire\CashAndBanks\Categories\BankCategoriesIndex;
use Modules\Finance\Livewire\CashAndBanks\ChecksBooksTable;
use Modules\Finance\Livewire\CashAndBanks\ChecksTable;
use Modules\Finance\Livewire\CashAndBanks\Collections\CollectionsIndex;
use Modules\Finance\Livewire\CashAndBanks\CollectionsTable;
use Modules\Finance\Livewire\CashAndBanks\InternalAdjust\InternalAdjustsIndex;
use Modules\Finance\Livewire\CashAndBanks\InternalAdjustsTable;
use Modules\Finance\Livewire\CashAndBanks\PaymentDisbursements\PaymentDisbursementsIndex;
use Modules\Finance\Livewire\CashAndBanks\PaymentDisbursementsTable;
use Modules\Finance\Livewire\CashAndBanks\Safes\SafesIndex;
use Modules\Finance\Livewire\CashAndBanks\SafesTable;
use Modules\Finance\Livewire\GeneralLedger\AccountCategories\AccountCategoriesIndex;
use Modules\Finance\Livewire\GeneralLedger\AccountCategories\AccountCategoriesTable;
use Modules\Finance\Livewire\GeneralLedger\AccountGroups\AccountGroupAccountsTable;
use Modules\Finance\Livewire\GeneralLedger\AccountGroups\AccountGroupsIndex;
use Modules\Finance\Livewire\GeneralLedger\AccountGroups\AccountGroupsTable;
use Modules\Finance\Livewire\GeneralLedger\Accounts\AccountChildrenTable;
use Modules\Finance\Livewire\GeneralLedger\Accounts\AccountsIndex;
use Modules\Finance\Livewire\GeneralLedger\Accounts\AccountsTable;
use Modules\Finance\Livewire\GeneralLedger\Charts\ChartAccountsTable;
use Modules\Finance\Livewire\GeneralLedger\Charts\ChartsIndex;
use Modules\Finance\Livewire\GeneralLedger\Charts\ChartsTable;
use Modules\Finance\Livewire\GeneralLedger\CostCenters\CostCentersIndex;
use Modules\Finance\Livewire\GeneralLedger\CostCenters\CostCentersTable;
use Modules\Finance\Livewire\GeneralLedger\ExchangeRates\ExchangeRatesIndex;
use Modules\Finance\Livewire\GeneralLedger\ExchangeRates\ExchangeRatesTable;
use Modules\Finance\Livewire\GeneralLedger\FiscalYears\FiscalPeriodsTable;
use Modules\Finance\Livewire\GeneralLedger\FiscalYears\FiscalYearsIndex;
use Modules\Finance\Livewire\GeneralLedger\FiscalYears\FiscalYearsTable;
use Modules\Finance\Livewire\GeneralLedger\JournalBooks\JournalBookLedgersTable;
use Modules\Finance\Livewire\GeneralLedger\JournalBooks\JournalBooksIndex;
use Modules\Finance\Livewire\GeneralLedger\JournalBooks\JournalBooksTable;
use Modules\Finance\Livewire\GeneralLedger\Journals\JournalEditor;
use Modules\Finance\Livewire\GeneralLedger\Journals\JournalLinesTable;
use Modules\Finance\Livewire\GeneralLedger\Journals\JournalsIndex;
use Modules\Finance\Livewire\GeneralLedger\Journals\JournalsTable;
use Modules\Finance\Livewire\GeneralLedger\Ledgers\LedgersIndex;
use Modules\Finance\Livewire\GeneralLedger\Ledgers\LedgersTable;
use Modules\Finance\Livewire\Tax\TaxAdjustments\TaxAdjustmentsIndex;
use Modules\Finance\Livewire\Tax\TaxAdjustments\TaxAdjustmentsTable;
use Modules\Finance\Livewire\Tax\TaxCategories\TaxCategoriesIndex;
use Modules\Finance\Livewire\Tax\TaxCategories\TaxCategoriesTable;
use Modules\Finance\Livewire\Tax\Taxes\TaxesIndex;
use Modules\Finance\Livewire\Tax\Taxes\TaxesTable;
use Modules\Finance\Livewire\Tax\TaxGlLinks\TaxGlLinksIndex;
use Modules\Finance\Livewire\Tax\TaxGlLinks\TaxGlLinksTable;
use Modules\Finance\System\AccountsPayable\ApInvoiceForm;
use Modules\Finance\System\AccountsPayable\ApInvoiceRecordReferenceProvider;
use Modules\Finance\System\AccountsPayable\ApInvoiceRecordView as ApInvoiceRecordViewDefinition;
use Modules\Finance\System\AccountsPayable\DeductionCategoryForm;
use Modules\Finance\System\AccountsPayable\DeductionCategoryRecordReferenceProvider;
use Modules\Finance\System\AccountsPayable\DeductionCategoryRecordView as DeductionCategoryRecordViewDefinition;
use Modules\Finance\System\AccountsPayable\DeductionForm;
use Modules\Finance\System\AccountsPayable\DeductionGlLinkForm;
use Modules\Finance\System\AccountsPayable\DeductionGlLinkRecordReferenceProvider;
use Modules\Finance\System\AccountsPayable\DeductionGlLinkRecordView as DeductionGlLinkRecordViewDefinition;
use Modules\Finance\System\AccountsPayable\DeductionRecordReferenceProvider;
use Modules\Finance\System\AccountsPayable\DeductionRecordView as DeductionRecordViewDefinition;
use Modules\Finance\System\AccountsPayable\VendorProfileForm;
use Modules\Finance\System\AccountsPayable\VendorProfileRecordReferenceProvider;
use Modules\Finance\System\AccountsPayable\VendorProfileRecordView as VendorProfileRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\BankAccountForm;
use Modules\Finance\System\CashAndBanks\BankAccountRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\BankAccountRecordView as BankAccountRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\BankCategoryForm;
use Modules\Finance\System\CashAndBanks\BankCategoryRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\BankCategoryRecordView as BankCategoryRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\BankExpenseForm;
use Modules\Finance\System\CashAndBanks\BankExpenseRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\BankExpenseRecordView as BankExpenseRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\BankForm;
use Modules\Finance\System\CashAndBanks\BankRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\BankRecordView as BankRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\CheckForm;
use Modules\Finance\System\CashAndBanks\CheckRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\CheckRecordView as CheckRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\ChecksBookForm;
use Modules\Finance\System\CashAndBanks\ChecksBookRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\ChecksBookRecordView as ChecksBookRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\CollectionForm;
use Modules\Finance\System\CashAndBanks\CollectionRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\CollectionRecordView as CollectionRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\InternalAdjustForm;
use Modules\Finance\System\CashAndBanks\InternalAdjustRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\InternalAdjustRecordView as InternalAdjustRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\PaymentDisbursementForm;
use Modules\Finance\System\CashAndBanks\PaymentDisbursementRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\PaymentDisbursementRecordView as PaymentDisbursementRecordViewDefinition;
use Modules\Finance\System\CashAndBanks\SafeForm;
use Modules\Finance\System\CashAndBanks\SafeRecordReferenceProvider;
use Modules\Finance\System\CashAndBanks\SafeRecordView as SafeRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\AccountCategoryForm;
use Modules\Finance\System\GeneralLedger\AccountCategoryRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\AccountCategoryRecordView as AccountCategoryRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\AccountForm;
use Modules\Finance\System\GeneralLedger\AccountGroupForm;
use Modules\Finance\System\GeneralLedger\AccountGroupRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\AccountGroupRecordView as AccountGroupRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\AccountRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\AccountRecordView as AccountRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\ChartForm;
use Modules\Finance\System\GeneralLedger\ChartRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\ChartRecordView as ChartRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\CostCenterForm;
use Modules\Finance\System\GeneralLedger\CostCenterRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\CostCenterRecordView as CostCenterRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\ExchangeRateForm;
use Modules\Finance\System\GeneralLedger\ExchangeRateRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\ExchangeRateRecordView as ExchangeRateRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\FiscalYearForm;
use Modules\Finance\System\GeneralLedger\FiscalYearRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\FiscalYearRecordView as FiscalYearRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\JournalBookForm;
use Modules\Finance\System\GeneralLedger\JournalBookRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\JournalBookRecordView as JournalBookRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\JournalForm;
use Modules\Finance\System\GeneralLedger\JournalRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\JournalRecordView as JournalRecordViewDefinition;
use Modules\Finance\System\GeneralLedger\LedgerForm;
use Modules\Finance\System\GeneralLedger\LedgerRecordReferenceProvider;
use Modules\Finance\System\GeneralLedger\LedgerRecordView as LedgerRecordViewDefinition;
use Modules\Finance\System\Tax\TaxAdjustmentForm;
use Modules\Finance\System\Tax\TaxAdjustmentRecordReferenceProvider;
use Modules\Finance\System\Tax\TaxAdjustmentRecordView as TaxAdjustmentRecordViewDefinition;
use Modules\Finance\System\Tax\TaxCategoryForm;
use Modules\Finance\System\Tax\TaxCategoryRecordReferenceProvider;
use Modules\Finance\System\Tax\TaxCategoryRecordView as TaxCategoryRecordViewDefinition;
use Modules\Finance\System\Tax\TaxForm;
use Modules\Finance\System\Tax\TaxGlLinkForm;
use Modules\Finance\System\Tax\TaxGlLinkRecordReferenceProvider;
use Modules\Finance\System\Tax\TaxGlLinkRecordView as TaxGlLinkRecordViewDefinition;
use Modules\Finance\System\Tax\TaxRecordReferenceProvider;
use Modules\Finance\System\Tax\TaxRecordView as TaxRecordViewDefinition;
use Nwidart\Modules\Support\ModuleServiceProvider;

class FinanceServiceProvider extends ModuleServiceProvider
{
    /**
     * The name of the module.
     */
    protected string $name = 'Finance';

    /**
     * The lowercase version of the module name.
     */
    protected string $nameLower = 'finance';

    /**
     * Provider classes to register.
     *
     * @var string[]
     */
    protected array $providers = [
        EventServiceProvider::class,
        RouteServiceProvider::class,
    ];

    public function boot(): void
    {
        parent::boot();

        Livewire::component('finance.account-categories-index', AccountCategoriesIndex::class);
        Livewire::component('finance.account-categories-table', AccountCategoriesTable::class);
        Livewire::component('finance.accounts-index', AccountsIndex::class);
        Livewire::component('finance.accounts-table', AccountsTable::class);
        Livewire::component('finance.account-children-table', AccountChildrenTable::class);
        Livewire::component('finance.charts-index', ChartsIndex::class);
        Livewire::component('finance.charts-table', ChartsTable::class);
        Livewire::component('finance.chart-accounts-table', ChartAccountsTable::class);
        Livewire::component('finance.exchange-rates-index', ExchangeRatesIndex::class);
        Livewire::component('finance.exchange-rates-table', ExchangeRatesTable::class);
        Livewire::component('finance.fiscal-years-index', FiscalYearsIndex::class);
        Livewire::component('finance.fiscal-years-table', FiscalYearsTable::class);
        Livewire::component('finance.fiscal-periods-table', FiscalPeriodsTable::class);
        Livewire::component('finance.ledgers-index', LedgersIndex::class);
        Livewire::component('finance.ledgers-table', LedgersTable::class);
        Livewire::component('finance.journal-books-index', JournalBooksIndex::class);
        Livewire::component('finance.journal-books-table', JournalBooksTable::class);
        Livewire::component('finance.journal-book-ledgers-table', JournalBookLedgersTable::class);
        Livewire::component('finance.journals-index', JournalsIndex::class);
        Livewire::component('finance.journals-table', JournalsTable::class);
        Livewire::component('finance.journal-lines-table', JournalLinesTable::class);
        Livewire::component('finance.journal-editor', JournalEditor::class);
        Livewire::component('finance.cost-centers-index', CostCentersIndex::class);
        Livewire::component('finance.cost-centers-table', CostCentersTable::class);
        Livewire::component('finance.account-groups-index', AccountGroupsIndex::class);
        Livewire::component('finance.account-groups-table', AccountGroupsTable::class);
        Livewire::component('finance.account-group-accounts-table', AccountGroupAccountsTable::class);
        Livewire::component('finance.vendor-profiles-index', VendorProfilesIndex::class);
        Livewire::component('finance.vendor-profiles-table', VendorProfilesTable::class);
        Livewire::component('finance.invoices-index', ApInvoicesIndex::class);
        Livewire::component('finance.invoices-table', ApInvoicesTable::class);
        Livewire::component('finance.invoice-lines-table', ApInvoiceLinesTable::class);
        Livewire::component('finance.invoice-line-editor', ApInvoiceLineEditor::class);
        Livewire::component('finance.invoice-tax-lines-table', ApInvoiceTaxLinesTable::class);
        Livewire::component('finance.invoice-tax-line-editor', ApInvoiceTaxLineEditor::class);
        Livewire::component('finance.invoice-deduction-lines-table', ApInvoiceDeductionLinesTable::class);
        Livewire::component('finance.invoice-deduction-line-editor', ApInvoiceDeductionLineEditor::class);
        Livewire::component('finance.deduction-categories-index', DeductionCategoriesIndex::class);
        Livewire::component('finance.deduction-categories-table', DeductionCategoriesTable::class);
        Livewire::component('finance.deductions-index', DeductionsIndex::class);
        Livewire::component('finance.deductions-table', DeductionsTable::class);
        Livewire::component('finance.deduction-gl-links-index', DeductionGlLinksIndex::class);
        Livewire::component('finance.deduction-gl-links-table', DeductionGlLinksTable::class);
        Livewire::component('finance.tax-categories-index', TaxCategoriesIndex::class);
        Livewire::component('finance.tax-categories-table', TaxCategoriesTable::class);
        Livewire::component('finance.taxes-index', TaxesIndex::class);
        Livewire::component('finance.taxes-table', TaxesTable::class);
        Livewire::component('finance.tax-gl-links-index', TaxGlLinksIndex::class);
        Livewire::component('finance.tax-gl-links-table', TaxGlLinksTable::class);
        Livewire::component('finance.tax-adjustments-index', TaxAdjustmentsIndex::class);
        Livewire::component('finance.tax-adjustments-table', TaxAdjustmentsTable::class);

        Livewire::component('finance.bank-categories-index', BankCategoriesIndex::class);
        Livewire::component('finance.bank-categories-table', BankCategoriesTable::class);
        Livewire::component('finance.banks-index', BanksIndex::class);
        Livewire::component('finance.banks-table', BanksTable::class);
        Livewire::component('finance.bank-accounts-index', BankAccountsIndex::class);
        Livewire::component('finance.bank-accounts-table', BankAccountsTable::class);
        Livewire::component('finance.checks-books-index', ChecksBooksIndex::class);
        Livewire::component('finance.checks-books-table', ChecksBooksTable::class);
        Livewire::component('finance.checks-index', ChecksIndex::class);
        Livewire::component('finance.checks-table', ChecksTable::class);
        Livewire::component('finance.safes-index', SafesIndex::class);
        Livewire::component('finance.safes-table', SafesTable::class);
        Livewire::component('finance.internal-adjusts-index', InternalAdjustsIndex::class);
        Livewire::component('finance.internal-adjusts-table', InternalAdjustsTable::class);
        Livewire::component('finance.bank-expenses-index', BankExpensesIndex::class);
        Livewire::component('finance.bank-expenses-table', BankExpensesTable::class);
        Livewire::component('finance.payment-disbursements-index', PaymentDisbursementsIndex::class);
        Livewire::component('finance.payment-disbursements-table', PaymentDisbursementsTable::class);
        Livewire::component('finance.collections-index', CollectionsIndex::class);
        Livewire::component('finance.collections-table', CollectionsTable::class);

        $recordReferenceRegistry = $this->app->make(RecordReferenceRegistry::class);
        $recordReferenceRegistry->register(new AccountCategoryRecordReferenceProvider);
        $recordReferenceRegistry->register(new AccountRecordReferenceProvider);
        $recordReferenceRegistry->register(new ChartRecordReferenceProvider);
        $recordReferenceRegistry->register(new ExchangeRateRecordReferenceProvider);
        $recordReferenceRegistry->register(new FiscalYearRecordReferenceProvider);
        $recordReferenceRegistry->register(new LedgerRecordReferenceProvider);
        $recordReferenceRegistry->register(new JournalBookRecordReferenceProvider);
        $recordReferenceRegistry->register(new JournalRecordReferenceProvider);
        $recordReferenceRegistry->register(new CostCenterRecordReferenceProvider);
        $recordReferenceRegistry->register(new AccountGroupRecordReferenceProvider);
        $recordReferenceRegistry->register(new VendorProfileRecordReferenceProvider);
        $recordReferenceRegistry->register(new ApInvoiceRecordReferenceProvider);
        $recordReferenceRegistry->register(new DeductionCategoryRecordReferenceProvider);
        $recordReferenceRegistry->register(new DeductionRecordReferenceProvider);
        $recordReferenceRegistry->register(new DeductionGlLinkRecordReferenceProvider);
        $recordReferenceRegistry->register(new TaxCategoryRecordReferenceProvider);
        $recordReferenceRegistry->register(new TaxRecordReferenceProvider);
        $recordReferenceRegistry->register(new TaxGlLinkRecordReferenceProvider);
        $recordReferenceRegistry->register(new TaxAdjustmentRecordReferenceProvider);
        $recordReferenceRegistry->register(new BankCategoryRecordReferenceProvider);
        $recordReferenceRegistry->register(new BankRecordReferenceProvider);
        $recordReferenceRegistry->register(new BankAccountRecordReferenceProvider);
        $recordReferenceRegistry->register(new ChecksBookRecordReferenceProvider);
        $recordReferenceRegistry->register(new CheckRecordReferenceProvider);
        $recordReferenceRegistry->register(new SafeRecordReferenceProvider);
        $recordReferenceRegistry->register(new InternalAdjustRecordReferenceProvider);
        $recordReferenceRegistry->register(new BankExpenseRecordReferenceProvider);

        $recordViewRegistry = $this->app->make(RecordViewRegistry::class);
        $recordViewRegistry->register('finance.general-ledger.account-category', AccountCategoryRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.account', AccountRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.chart', ChartRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.exchange-rate', ExchangeRateRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.fiscal-year', FiscalYearRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.ledger', LedgerRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.journal-book', JournalBookRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.journal', JournalRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.cost-center', CostCenterRecordViewDefinition::class);
        $recordViewRegistry->register('finance.general-ledger.account-group', AccountGroupRecordViewDefinition::class);
        $recordViewRegistry->register('finance.accounts-payable.vendor-profile', VendorProfileRecordViewDefinition::class);
        $recordViewRegistry->register('finance.accounts-payable.invoice', ApInvoiceRecordViewDefinition::class);
        $recordViewRegistry->register('finance.accounts-payable.deduction-category', DeductionCategoryRecordViewDefinition::class);
        $recordViewRegistry->register('finance.accounts-payable.deduction', DeductionRecordViewDefinition::class);
        $recordViewRegistry->register('finance.accounts-payable.deduction-gl-link', DeductionGlLinkRecordViewDefinition::class);
        $recordViewRegistry->register('finance.tax.tax-category', TaxCategoryRecordViewDefinition::class);
        $recordViewRegistry->register('finance.tax.tax', TaxRecordViewDefinition::class);
        $recordViewRegistry->register('finance.tax.tax-gl-link', TaxGlLinkRecordViewDefinition::class);
        $recordViewRegistry->register('finance.tax.tax-adjustment', TaxAdjustmentRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.bank-category', BankCategoryRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.bank', BankRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.bank-account', BankAccountRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.checks-book', ChecksBookRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.check', CheckRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.safe', SafeRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.internal-adjust', InternalAdjustRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.bank-expense', BankExpenseRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.payment-disbursement', PaymentDisbursementRecordViewDefinition::class);
        $recordViewRegistry->register('finance.cash-and-banks.collection', CollectionRecordViewDefinition::class);

        $formRegistry = $this->app->make(FormDefinitionRegistry::class);
        $formRegistry->register('finance.general-ledger.account-category.create', AccountCategoryForm::class);
        $formRegistry->register('finance.general-ledger.account.create', AccountForm::class);
        $formRegistry->register('finance.general-ledger.chart.create', ChartForm::class);
        $formRegistry->register('finance.general-ledger.exchange-rate.create', ExchangeRateForm::class);
        $formRegistry->register('finance.general-ledger.fiscal-year.create', FiscalYearForm::class);
        $formRegistry->register('finance.general-ledger.ledger.create', LedgerForm::class);
        $formRegistry->register('finance.general-ledger.journal-book.create', JournalBookForm::class);
        $formRegistry->register('finance.general-ledger.journal.create', JournalForm::class);
        $formRegistry->register('finance.general-ledger.cost-center.create', CostCenterForm::class);
        $formRegistry->register('finance.general-ledger.account-group.create', AccountGroupForm::class);
        $formRegistry->register('finance.accounts-payable.vendor-profile.create', VendorProfileForm::class);
        $formRegistry->register('finance.accounts-payable.invoice.create', ApInvoiceForm::class);
        $formRegistry->register('finance.accounts-payable.deduction-category.create', DeductionCategoryForm::class);
        $formRegistry->register('finance.accounts-payable.deduction.create', DeductionForm::class);
        $formRegistry->register('finance.accounts-payable.deduction-gl-link.create', DeductionGlLinkForm::class);
        $formRegistry->register('finance.tax.tax-category.create', TaxCategoryForm::class);
        $formRegistry->register('finance.tax.tax.create', TaxForm::class);
        $formRegistry->register('finance.tax.tax-gl-link.create', TaxGlLinkForm::class);
        $formRegistry->register('finance.tax.tax-adjustment.create', TaxAdjustmentForm::class);
        $formRegistry->register('finance.cash-and-banks.bank-category.create', BankCategoryForm::class);
        $formRegistry->register('finance.cash-and-banks.bank.create', BankForm::class);
        $formRegistry->register('finance.cash-and-banks.bank-account.create', BankAccountForm::class);
        $formRegistry->register('finance.cash-and-banks.checks-book.create', ChecksBookForm::class);
        $formRegistry->register('finance.cash-and-banks.check.create', CheckForm::class);
        $formRegistry->register('finance.cash-and-banks.safe.create', SafeForm::class);
        $formRegistry->register('finance.cash-and-banks.internal-adjust.create', InternalAdjustForm::class);
        $formRegistry->register('finance.cash-and-banks.bank-expense.create', BankExpenseForm::class);
        $formRegistry->register('finance.cash-and-banks.payment-disbursement.create', PaymentDisbursementForm::class);
        $formRegistry->register('finance.cash-and-banks.collection.create', CollectionForm::class);

        $recordReferenceRegistry->register(new PaymentDisbursementRecordReferenceProvider);
        $recordReferenceRegistry->register(new CollectionRecordReferenceProvider);
    }
}
