<?php

namespace Modules\Inventory\System\Warehousing;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\HR\Models\OrganizationStructure\Branch;
use Modules\Inventory\Models\Warehouse;

/**
 * Create/edit-form definition for the "inv-whs-wrh" Application. Code and
 * slug are generated by Warehouse::booted(), so neither is a field here.
 */
class WarehouseForm extends DynamicForm
{
    public function model(): string
    {
        return Warehouse::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required()->rules(['max:255']),
            TextField::make('capacity_m3')
                ->type('number')
                ->label('Capacity (m³)')
                ->required()
                ->rules(['numeric', 'min:0']),
            RelationListField::make('branch')
                ->model(Branch::class)
                ->field('name')
                ->column('branch_id')
                ->label('Branch'),
        ];
    }
}
