<?php

namespace App\Models;

use Spatie\Permission\Models\Permission as SpatiePermission;
use Spatie\Translatable\Attributes\Translatable;
use Spatie\Translatable\HasTranslations;

/**
 * The Spatie permission with a translated `description` — the human-readable
 * label the Security → Permissions catalog shows instead of the raw
 * "fin-gl-jou.post" name. Generated by App\Console\Commands\SyncPermissionsCommand
 * from the owning node's own translated name, never written by hand.
 *
 * Bound as the Spatie permission model in config/permission.php, exactly as
 * App\Models\Role is, so every ->can()/->givePermissionTo() call keeps
 * working unmodified. Translation is handled the same way as every other
 * translated model here (Application, Module, SubModule) rather than by
 * hand-rolled json_encode/json_decode at each call site.
 */
#[Translatable('description')]
class Permission extends SpatiePermission
{
    use HasTranslations;
}
