<?php

namespace Modules\HR\System\OrganizationStructure;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\SelectField;
use App\Support\DynamicForm\Core\Fields\TextareaField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\General\Models\World\City;
use Modules\HR\Models\OrganizationStructure\Branch;
use Modules\HR\Models\OrganizationStructure\Entity;

/**
 * Create-form definition for the "hr-org-brn" Application. Branch::code and
 * Branch::slug are generated by the model's own creating() hook — this form
 * only ever supplies the raw business fields.
 */
class BranchForm extends DynamicForm
{
    public function model(): string
    {
        return Branch::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            RelationListField::make('entity')
                ->model(Entity::class)
                ->field('name')
                ->column('entity_id')
                ->label('Entity')
                ->required(),
            SelectField::make('is_main')
                ->label('Main Branch')
                ->options(['1' => 'Yes', '0' => 'No'])
                ->rules(['boolean']),
            RelationListField::make('city')
                ->model(City::class)
                ->field('name')
                ->column('city_id')
                ->label('City'),
            TextareaField::make('address')->label('Address'),
            TextField::make('phone')->type('tel')->label('Phone'),
        ];
    }
}
