<?php

namespace Modules\HR\System\OrganizationStructure;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\HR\Models\OrganizationStructure\Department;

/**
 * Create-form definition for the "hr-org-dep" Application. Department::code
 * and Department::slug are generated by the model's own creating() hook —
 * this form only ever supplies the raw business fields.
 *
 * A department is a group-wide catalog entry, entity-agnostic by design —
 * attaching it to specific entities/branches (department_entity) happens
 * afterward against the saved record, the same "create first, attach after"
 * shape as Person's Positions.
 */
class DepartmentForm extends DynamicForm
{
    public function model(): string
    {
        return Department::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            RelationListField::make('parent_department')
                ->model(Department::class)
                ->createForm('hr.organization-structure.department.create')
                ->field('name')
                ->column('parent_department_id')
                ->label('Parent Department'),
        ];
    }
}
