<?php

namespace Modules\HR\System\OrganizationStructure;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\General\Models\World\Companies\Company;
use Modules\General\Models\World\Currency;
use Modules\HR\Models\OrganizationStructure\Entity;

/**
 * Create-form definition for the "hr-org-ent" Application. Entity::code and
 * Entity::slug are generated by the model's own creating() hook — this form
 * only ever supplies the raw business fields.
 *
 * The company picker is deliberately narrowed to companies that already
 * have both a tax_id and a commercial_registration on file — an entity is
 * only ever created once its underlying company record has proven it,
 * matching the business rule agreed for entity/company linking.
 */
class EntityForm extends DynamicForm
{
    public function model(): string
    {
        return Entity::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            RelationListField::make('company')
                ->model(Company::class)
                ->createForm('general.world.company.create')
                ->field('name')
                ->searchable(['name', 'tax_id', 'commercial_registration'])
                ->query(fn ($query) => $query->whereNotNull('tax_id')->whereNotNull('commercial_registration'))
                ->column('company_id')
                ->label('Company')
                ->required(),
            RelationListField::make('parent_entity')
                ->model(Entity::class)
                ->createForm('hr.organization-structure.entity.create')
                ->field('name')
                ->column('parent_entity_id')
                ->label('Parent Entity'),
            RelationListField::make('currency')
                ->model(Currency::class)
                ->field('name')
                ->column('currency_id')
                ->label('Currency'),
            TextField::make('legal_form')->label('Legal Form'),
            TextField::make('fiscal_year_start_month')->type('number')->label('Fiscal Year Start Month')->rules(['integer', 'min:1', 'max:12']),
            TextField::make('fiscal_year_start_day')->type('number')->label('Fiscal Year Start Day')->rules(['integer', 'min:1', 'max:31']),
            TextField::make('ownership_percentage')->type('number')->label('Ownership Percentage')->rules(['numeric', 'min:0', 'max:100']),
            TextField::make('tax_authority')->label('Tax Authority'),
        ];
    }
}
