<?php

namespace Modules\HR\System\OrganizationStructure;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\HR\Models\OrganizationStructure\JobGrade;

/**
 * Create-form definition for the "hr-org-jbg" Application. JobGrade::code
 * and JobGrade::slug are generated by the model's own creating() hook —
 * this form only ever supplies the raw business fields.
 *
 * Which job titles this grade is valid for (job_title_grade) is attached
 * afterward from the Job Title side, not here — same "create first, attach
 * after" shape as Department/Entity attachments.
 */
class JobGradeForm extends DynamicForm
{
    public function model(): string
    {
        return JobGrade::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            TextField::make('level')->type('number')->label('Level')->required()->rules(['integer', 'min:1']),
        ];
    }
}
