<?php

namespace Modules\HR\System\OrganizationStructure;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\HR\Models\OrganizationStructure\Department;
use Modules\HR\Models\OrganizationStructure\JobTitle;

/**
 * Create-form definition for the "hr-org-jbt" Application. JobTitle::code
 * and JobTitle::slug are generated by the model's own creating() hook —
 * this form only ever supplies the raw business fields.
 *
 * Which grades this title allows (job_title_grade) is attached afterward
 * against the saved record, not here — same "create first, attach after"
 * shape as Department/Entity attachments.
 */
class JobTitleForm extends DynamicForm
{
    public function model(): string
    {
        return JobTitle::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            RelationListField::make('department')
                ->model(Department::class)
                ->createForm('hr.organization-structure.department.create')
                ->field('name')
                ->column('department_id')
                ->label('Department')
                ->required(),
        ];
    }
}
