<?php

namespace Modules\General\System\Security;

use App\Models\Permission;
use App\Services\NavigationTreeService;
use App\Support\DynamicRecordView\Core\Content\FieldsContent;
use App\Support\DynamicRecordView\Core\DynamicRecordView;
use App\Support\DynamicRecordView\Core\Fields\ComputedViewField;
use App\Support\DynamicRecordView\Core\Fields\TextViewField;
use App\Support\DynamicRecordView\Core\RecordTab;
use App\Support\DynamicRecordView\Core\SubApplication;
use App\Support\RecordReference\RecordReferenceAccess;
use Illuminate\Database\Eloquent\Builder;
use Modules\General\Livewire\Security\Permissions\PermissionRolesTable;

/**
 * The authorized record show page for a single Permission (gen-sec-per).
 * Read-only by definition: permissions are generated by `permissions:sync`
 * from the module/sub_module/application hierarchy and never edited here —
 * the page exists to answer "what is this name, and who holds it".
 */
class PermissionRecordView extends DynamicRecordView
{
    protected string $viewKey = 'general.security.permission';

    public function model(): string
    {
        return Permission::class;
    }

    public function query(): Builder
    {
        $application = app(NavigationTreeService::class)->getApplicationByCode('gen-sec-per');

        if (! app(RecordReferenceAccess::class)->applicationAccessible($application)) {
            return Permission::query()->whereRaw('1 = 0');
        }

        return Permission::query();
    }

    public function applicationCode(): ?string
    {
        return 'gen-sec-per';
    }

    public function title(mixed $record): string
    {
        return (string) $record->name;
    }

    public function subtitle(mixed $record): ?string
    {
        return $record->description ?: null;
    }

    public function tabs(): array
    {
        return [
            RecordTab::make('overview')
                ->label('Overview')
                ->default()
                ->contents([
                    FieldsContent::make('basic-information')
                        ->heading('Basic Information')
                        ->fields([
                            TextViewField::make('name')->label('Permission'),
                            TextViewField::make('description')->label('Description'),
                            TextViewField::make('guard_name')->label('Guard'),
                            // The two halves the name is built from, so the
                            // page explains the naming scheme rather than
                            // just repeating it.
                            ComputedViewField::make('owner_code')
                                ->label('Belongs To')
                                ->using(fn (mixed $record): string => (string) str($record->name)->beforeLast('.')),
                            ComputedViewField::make('action')
                                ->label('Action')
                                ->using(fn (mixed $record): string => (string) str($record->name)->afterLast('.')),
                        ]),
                ]),
        ];
    }

    public function subApplications(): array
    {
        return [
            SubApplication::make('roles')
                ->label('Roles')
                ->table(PermissionRolesTable::class)
                ->relation('roles')
                ->default(),
        ];
    }
}
