<?php

namespace Modules\HR\System\EmployeeManagement;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\DateField;
use App\Support\DynamicForm\Core\Fields\RelationListField;
use App\Support\DynamicForm\Core\Fields\SelectField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\General\Models\World\People\Person;
use Modules\HR\Models\EmployeeManagement\Employee;
use Modules\HR\Models\OrganizationStructure\Branch;
use Modules\HR\Models\OrganizationStructure\Department;
use Modules\HR\Models\OrganizationStructure\Entity;
use Modules\HR\Models\OrganizationStructure\JobGrade;
use Modules\HR\Models\OrganizationStructure\JobTitle;

/**
 * Create-form definition for the "hr-emp-emp" Application. Employee::code
 * and Employee::slug are generated by the model's own creating() hook —
 * this form only ever supplies the raw business fields.
 *
 * The pickers below are independent (no client-side cascading engine exists
 * yet to narrow branch by entity, department by entity, job title by
 * department, or job grade by job title as they're selected) — the actual
 * enforcement of that chain is Employee::assertOrganizationallyConsistent(),
 * which runs on every save regardless of which UI produced it.
 */
class EmployeeForm extends DynamicForm
{
    public function model(): string
    {
        return Employee::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('employee_number')->label('Employee Number')->required(),
            RelationListField::make('person')
                ->model(Person::class)
                ->createForm('general.world.person.create')
                ->field('full_name')
                ->searchable(['full_name', 'national_id', 'passport_number'])
                ->column('person_id')
                ->label('Person')
                ->required(),
            RelationListField::make('entity')
                ->model(Entity::class)
                ->createForm('hr.organization-structure.entity.create')
                ->field('name')
                ->column('entity_id')
                ->label('Entity')
                ->required(),
            RelationListField::make('branch')
                ->model(Branch::class)
                ->createForm('hr.organization-structure.branch.create')
                ->field('name')
                ->column('branch_id')
                ->label('Branch')
                ->required(),
            RelationListField::make('department')
                ->model(Department::class)
                ->createForm('hr.organization-structure.department.create')
                ->field('name')
                ->column('department_id')
                ->label('Department')
                ->required(),
            RelationListField::make('job_title')
                ->model(JobTitle::class)
                ->createForm('hr.organization-structure.job-title.create')
                ->field('name')
                ->column('job_title_id')
                ->label('Job Title')
                ->required(),
            RelationListField::make('job_grade')
                ->model(JobGrade::class)
                ->createForm('hr.organization-structure.job-grade.create')
                ->field('name')
                ->column('job_grade_id')
                ->label('Job Grade')
                ->required(),
            SelectField::make('entity_scope')
                ->label('Entity Scope')
                ->options([
                    'own' => 'Own Records Only',
                    'branch' => 'Own Branch',
                    'entity' => 'Whole Entity',
                    'entity_tree' => 'Entity + Descendants',
                ])
                ->required(),
            SelectField::make('department_scope')
                ->label('Department Scope')
                ->options([
                    'own' => 'Own Records Only',
                    'department' => 'This Department',
                    'department_tree' => 'Department + Sub-departments',
                    'all' => 'Every Department',
                ])
                ->required(),
            TextField::make('gross_salary')->type('number')->label('Gross Salary')->rules(['numeric', 'min:0']),
            DateField::make('hire_date')->label('Hire Date')->required(),
        ];
    }
}
