<?php

namespace Modules\HR\System\Cycles;

use App\Support\DynamicForm\Core\DynamicForm;
use App\Support\DynamicForm\Core\Fields\TextareaField;
use App\Support\DynamicForm\Core\Fields\TextField;
use Modules\HR\Models\Cycles\CycleType;

/**
 * Create-form definition for the "hr-cyc-typ" Application. CycleType::code is
 * generated by the model's own creating() hook.
 */
class CycleTypeForm extends DynamicForm
{
    public function model(): string
    {
        return CycleType::class;
    }

    public function fields(): array
    {
        return [
            TextField::make('name')->label('Name')->required(),
            TextField::make('application_code')
                ->label('Application Code')
                ->helpText('Code of the App/SubModule that creates the subject documents, e.g. fin-ap-inv.')
                ->required(),
            TextareaField::make('description')->label('Description'),
        ];
    }
}
